# Generated by Django 5.1.1 on 2024-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_test',
            name='substance',
        ),
    ]
