# Generated by Django 5.1.1 on 2024-11-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_labtestwater_agency_labtestwater_intervention_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestwater',
            name='measure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
