# Generated by Django 5.1.1 on 2024-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtestwater_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestwater',
            name='sample_name',
            field=models.CharField(max_length=300),
        ),
    ]
