# Generated by Django 5.1.1 on 2024-12-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_labtestwater_sample_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestIndustrialSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30)),
                ('sample_type', models.CharField(max_length=30)),
                ('sample_name', models.CharField(max_length=300)),
                ('substance', models.CharField(max_length=300)),
                ('substance_agency', models.CharField(blank=True, max_length=300, null=True)),
                ('agency', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.FloatField()),
                ('under_limit', models.CharField(blank=True, max_length=300, null=True)),
                ('measure', models.CharField(blank=True, max_length=30, null=True)),
                ('intervention_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
