# Generated by Django 5.1.1 on 2024-12-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_labtestagriculturalsoil_labtestresidentialsoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestIndustrialSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30)),
                ('sample_type', models.CharField(max_length=30)),
                ('sample_name', models.CharField(max_length=300)),
                ('substance', models.CharField(max_length=300)),
                ('substance_agency', models.CharField(blank=True, max_length=300, null=True)),
                ('agency', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.FloatField()),
                ('under_limit', models.CharField(blank=True, max_length=300, null=True)),
                ('measure', models.CharField(blank=True, max_length=30, null=True)),
                ('carcinogenic', models.FloatField(blank=True, null=True)),
                ('noncarcinogenic', models.FloatField(blank=True, null=True)),
                ('rsl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResidentialSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30)),
                ('sample_type', models.CharField(max_length=30)),
                ('sample_name', models.CharField(max_length=300)),
                ('substance', models.CharField(max_length=300)),
                ('substance_agency', models.CharField(blank=True, max_length=300, null=True)),
                ('agency', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.FloatField()),
                ('under_limit', models.CharField(blank=True, max_length=300, null=True)),
                ('measure', models.CharField(blank=True, max_length=30, null=True)),
                ('carcinogenic', models.FloatField(blank=True, null=True)),
                ('noncarcinogenic', models.FloatField(blank=True, null=True)),
                ('rsl', models.FloatField()),
            ],
        ),
    ]
