# Generated by Django 5.1.1 on 2024-10-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('subs_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=30)),
                ('soil_vrq', models.CharField(blank=True, max_length=10, null=True)),
                ('soil_vp', models.FloatField(blank=True, null=True)),
                ('soil_vi_agricultural', models.FloatField(blank=True, null=True)),
                ('soil_vi_industrial', models.FloatField(blank=True, null=True)),
                ('soil_vi_residential', models.FloatField(blank=True, null=True)),
                ('groundwater_vi', models.FloatField(blank=True, null=True)),
                ('substance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regulatory_orgs.substance')),
            ],
        ),
        migrations.CreateModel(
            name='Cetesb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=30)),
                ('soil_vrq', models.CharField(blank=True, max_length=10, null=True)),
                ('soil_vp', models.FloatField(blank=True, null=True)),
                ('soil_vi_agricultural', models.FloatField(blank=True, null=True)),
                ('soil_vi_industrial', models.FloatField(blank=True, null=True)),
                ('soil_vi_residential', models.FloatField(blank=True, null=True)),
                ('groundwater_vi', models.FloatField(blank=True, null=True)),
                ('substance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regulatory_orgs.substance')),
            ],
        ),
    ]
