# Generated by Django 5.1.1 on 2024-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_lab_test_substance'),
        ('regulatory_orgs', '0002_cetesb_groundwater_grouped'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('agency', models.CharField(max_length=30)),
                ('intervention_value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conama',
            name='substance',
        ),
        migrations.DeleteModel(
            name='Cetesb',
        ),
        migrations.DeleteModel(
            name='Conama',
        ),
        migrations.DeleteModel(
            name='Substance',
        ),
    ]
