# Generated by Django 5.1.1 on 2024-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_orgs', '0003_regulationwater_remove_conama_substance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_lab', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('substance_agency', models.CharField(max_length=300)),
                ('agency', models.CharField(max_length=30)),
            ],
        ),
    ]
