# Generated by Django 5.1.1 on 2024-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_orgs', '0005_regulationindustrialsoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationAgriculturalSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('agency', models.CharField(max_length=30)),
                ('intervention_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegulationResidentialSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('agency', models.CharField(max_length=30)),
                ('intervention_value', models.FloatField()),
            ],
        ),
    ]
