# Generated by Django 5.1.1 on 2024-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_orgs', '0006_regulationagriculturalsoil_regulationresidentialsoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationIndustrialSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('agency', models.CharField(max_length=30)),
                ('carcinogenic', models.FloatField(blank=True, null=True)),
                ('noncarcinogenic', models.FloatField(blank=True, null=True)),
                ('rsl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegulationResidentialSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=30, null=True)),
                ('agency', models.CharField(max_length=30)),
                ('carcinogenic', models.FloatField(blank=True, null=True)),
                ('noncarcinogenic', models.FloatField(blank=True, null=True)),
                ('rsl', models.FloatField()),
            ],
        ),
    ]
